name: LazyClass
author: michael
category: Utilities
tags: [LazyClass, lazy, dynamic, class, loading, lazy loading]
current: 0.1
docs: 'http://github.com/michaelficarra/MooTools-LazyClass/blob/master/README.md'
#demo: ''
